export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import { auth } from '@/auth';
import postgres from 'postgres';
import {
  enforceRateLimit,
  parseRouteParams,
  routeUuidParamsSchema,
} from '@/app/lib/security/api-guard';
import { fetchInvoiceById } from '@/app/lib/data';
import { formatDateToLocal } from '@/app/lib/utils';
import { fetchCompanyProfileForWorkspace } from '@/app/lib/company-profile';
import { ensureWorkspaceContextForCurrentUser } from '@/app/lib/workspaces';

import type PDFDocumentType from 'pdfkit';
const PDFDocument = require('pdfkit/js/pdfkit.standalone') as typeof PDFDocumentType;

function formatAmountForPdf(amountCents: number) {
  const value = amountCents / 100;
  return `${value.toFixed(2)} EUR`;
}

function dataUrlToBuffer(dataUrl: string) {
  const commaIndex = dataUrl.indexOf(',');
  if (commaIndex === -1) return null;

  const base64 = dataUrl.slice(commaIndex + 1);
  if (!base64) return null;

  try {
    return Buffer.from(base64, 'base64');
  } catch {
    return null;
  }
}

async function buildInvoicePdf(input: {
  invoice: {
    id: string;
    customer_name: string;
    customer_email: string;
    status: string;
    date: string;
    amount: number;
    invoice_number: string | null;
  };
  company: {
    companyName: string;
    vatOrRegNumber: string;
    address: string;
    companyEmail: string;
    invoiceFooter: string;
    logoDataUrl: string | null;
  };
}) {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const logoX = 50;
    const logoY = 45;
    const logoFit: [number, number] = [160, 80];

    if (input.company.logoDataUrl) {
      const logoBuffer = dataUrlToBuffer(input.company.logoDataUrl);

      if (logoBuffer) {
        const sig = logoBuffer.subarray(0, 8).toString('hex');
        console.log('[pdf-logo-sig]', sig, 'bytes', logoBuffer.length);
        try {
          const logoArrayBuffer = logoBuffer.buffer.slice(
            logoBuffer.byteOffset,
            logoBuffer.byteOffset + logoBuffer.byteLength,
          );
          doc.image(logoArrayBuffer, logoX, logoY, { fit: logoFit });
        } catch (err) {
          console.error('[pdf-logo-error]', err);
        }
      }
    }

    const invoiceLabel = input.invoice.invoice_number ?? input.invoice.id.slice(0, 8);
    doc.fontSize(22).text(input.company.companyName || 'Lateless', 50, 120);
    doc.fontSize(14).text(`Invoice ${invoiceLabel}`, 50, 150);

    doc.moveDown(2);
    doc.fontSize(12).text('From');
    if (input.company.address) doc.text(input.company.address);
    if (input.company.vatOrRegNumber) doc.text(`VAT/Reg: ${input.company.vatOrRegNumber}`);
    if (input.company.companyEmail) doc.text(`Email: ${input.company.companyEmail}`);

    doc.moveDown();
    doc.fontSize(12).text('To');
    doc.text(input.invoice.customer_name);
    doc.text(input.invoice.customer_email);

    doc.moveDown();
    doc.fontSize(12).text(`Date: ${formatDateToLocal(input.invoice.date)}`);
    doc.text(`Status: ${input.invoice.status}`);
    doc.text(`Amount: ${formatAmountForPdf(input.invoice.amount)}`);

    const footer = input.company.invoiceFooter || 'Generated by Lateless';
    doc.fontSize(10).fillColor('#444444').text(footer, 50, 760, { width: 500 });

    doc.end();
  });
}

export async function GET(
  req: Request,
  props: { params: Promise<{ id: string }> },
) {
  const session = await auth();
  if (!session?.user?.email) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const userEmail = session.user.email.trim().toLowerCase();

  const rl = await enforceRateLimit(req, {
    bucket: 'invoice_pdf',
    windowSec: 60,
    ipLimit: 30,
    userLimit: 20,
  }, { userKey: userEmail });
  if (rl) return rl;

  const rawParams = await props.params;
  const parsedParams = parseRouteParams(routeUuidParamsSchema, rawParams);
  if (!parsedParams.ok) return parsedParams.response;
  const params = parsedParams.data;

  const context = await ensureWorkspaceContextForCurrentUser();

  const [invoice, companyProfile] = await Promise.all([
    fetchInvoiceById(params.id),
    fetchCompanyProfileForWorkspace(context.workspaceId),
  ]);

  if (!invoice) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 });
  }

  const pdfBuffer = await buildInvoicePdf({
    invoice,
    company: companyProfile,
  });
  const filenameId = invoice.invoice_number ?? invoice.id;

  return new NextResponse(pdfBuffer as unknown as BodyInit, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="invoice-${filenameId}.pdf"`,
      'Cache-Control': 'no-store, max-age=0',
    },
  });
}
